In [2]:
import numpy as np
from lapy import TriaMesh

First we create and initialize a TriaMesh. Note, this mesh is not oriented (some normals flip), so some functions below will complain until we fix the situation with .orient_() later.

In [3]:
points = [[0.0,0.0,0.0], [0,1,0], [1,1,0], [1,0,0],
          [0,0,1], [0,1,1], [1,1,1], [1,0,1]]
trias = [[0,1,2], [2,3,0], [4,5,6], [6,7,4], [0,4,7], [7,3,0],
         [0,4,5], [5,1,0], [1,5,6], [6,2,1], [3,7,6], [6,2,3]]

T = TriaMesh(points,trias)
# note, this mesh is not oriented, so some functions will complain below until we fix this

In [4]:
T.is_closed()

True

In [5]:
T.is_manifold()

True

In [6]:
T.is_oriented()

False

In [7]:
print(np.max(T.adj_dir))

2.0


In [8]:
T.euler()

2

In [9]:
T.tria_areas()

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [10]:
T.area()

5.999999999999998

In [11]:
T.volume()  # will fail for non-oriented meshes

ValueError: Error: Can only compute volume for oriented triangle meshes!

In [12]:
T.vertex_degrees()

array([6, 4, 4, 4, 4, 4, 6, 4])

In [13]:
T.vertex_areas()

array([1.        , 0.66666667, 0.66666667, 0.66666667, 0.66666667,
       0.66666667, 1.        , 0.66666667])

In [14]:
sum(T.vertex_areas())

6.0

In [15]:
T.avg_edge_length()

1.1380711874576983

In [16]:
T.tria_normals()

array([[ 0.,  0., -1.],
       [ 0., -0., -1.],
       [ 0.,  0., -1.],
       [ 0., -0., -1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [-1.,  0.,  0.],
       [-1.,  0., -0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [-1.,  0.,  0.],
       [-1.,  0., -0.]])

In [17]:
T.tria_qualities()

array([0.8660254, 0.8660254, 0.8660254, 0.8660254, 0.8660254, 0.8660254,
       0.8660254, 0.8660254, 0.8660254, 0.8660254, 0.8660254, 0.8660254])

In [18]:
T.has_free_vertices()

False

In [19]:
T.rm_free_vertices_()

(array([0, 1, 2, 3, 4, 5, 6, 7]), [])

In [20]:
T.orient_()

Searched mesh after 3 flooding iterations (0.0007233619689941406 sec).


6

In [21]:
T.is_oriented()

True

In [22]:
# Compute Volume (works only for oriented meshes)
T.volume() 

1.0

In [23]:
# Vertex normals averages tria normals (only oriented meshes)
T.vertex_normals()

array([[-0.57735027, -0.57735027, -0.57735027],
       [-0.40824829,  0.81649658, -0.40824829],
       [ 0.40824829,  0.40824829, -0.81649658],
       [ 0.81649658, -0.40824829, -0.40824829],
       [-0.40824829, -0.40824829,  0.81649658],
       [-0.81649658,  0.40824829,  0.40824829],
       [ 0.57735027,  0.57735027,  0.57735027],
       [ 0.40824829, -0.81649658,  0.40824829]])

In [24]:
T.normal_offset_(0.2*T.avg_edge_length())

In [25]:
Tbdr = TriaMesh(T.v,T.t[2:,:])

In [26]:
Tbdr.refine_()

In [27]:
print(Tbdr.boundary_loops())

[[0, 8, 1, 13, 2, 16, 3, 9]]
